#!/usr/bin/python

import sys
import subprocess
import glob

if len(sys.argv) <= 2:
    print("No commit message")
    raise SystemExit


msg = sys.argv[1]
files = sys.argv[2:]

directoryfiles = sorted(glob.glob("*"))
if msg in directoryfiles:
    print("Bad commit message: filename used instead of message")
    raise SystemExit

filenames = " ".join(files)

subprocess.call("git add %s"%filenames,shell=True)
subprocess.call("git commit -m \"%s\""%msg,shell=True)
subprocess.call("git push",shell=True)
